### ISSUE TITLE
forge support

### ISSUE THREAD

**Issue by FlufferyGR** [flathub/com.mojang.Minecraft#114]
when trying to install forge it gives this error
java.lang.UnsatisfiedLinkError: Can't load library: /usr/lib/jvm/java-11-openjdk-11.0.13.0.8-2.fc35.x86_64/lib/libawt_xawt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1873)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1399)
	at java.desktop/java.awt.Toolkit$3.run(Toolkit.java:1397)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1396)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1429)
	at java.desktop/javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:661)
	at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:166)
	at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:147)

**Comment by vchernin** [comment]
How are you trying to install it?

**Comment by FlufferyGR** [comment]
using `java -jar "file name"`
i fixxed the issue by using a newer version of openjdk
