### ISSUE TITLE
Failed to create window:  (game won't launch)

### ISSUE THREAD

**Issue by anthemion** [flathub/com.mojang.Minecraft#117]
I am running on a fresh install of Pop_os
I install the flatpack
I login with my microsoft account.
I click play
game window never opens

The game works fine with the PolyMC launcher flatpack when using Java 17

here is the log:

```
Minecraft client 1.18.1 is ready to start.
Starting!
Using default game log configuration client-1.12.xml (outputs XML)
Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
Setting user:
Backend library: LWJGL version 3.2.2 build 10
Failed to create window:
drp$a: GLFW error 65545: GLX: Failed to find a suitable GLXFBConfig
        at drp.b(SourceFile:218)
        at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36)
        at org.lwjgl.system.JNI.invokePPPP(Native Method)
        at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
        at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)
        at drp.<init>(SourceFile:92)
        at eqa.a(SourceFile:21)
        at dxo.<init>(SourceFile:476)
        at net.minecraft.client.main.Main.main(SourceFile:199)


Process ended with exit code 0
```

OS: Pop!_OS 21.10 x86_64 
Host: Pangolin pang11 
Kernel: 5.15.11-76051511-generic 
Resolution: 1920x1080 
DE: GNOME 40.5 
WM: Mutter 
CPU: AMD Ryzen 7 5700U with Radeon Graphics (16) @ 1.800GHz 
GPU: AMD ATI 05:00.0 Lucienne 
Memory: 5957MiB / 39533MiB

**Comment by anthemion** [comment]
I reinstalled the os without retaining the user profile and it worked....

I can't even reproduce the problem myself.
