### ISSUE TITLE
Narrator doesn't work

### ISSUE THREAD

**Issue by pizzadude** [flathub/com.mojang.Minecraft#14]
Press Ctrl + B to toggle Narrator. It shows "Narrator is not available"

Apparently requires "flite" to be installed on the linux host. 
https://bugs.mojang.com/browse/MC-114930

**Comment by AsciiWolf** [comment]
I have tried adding flite:
```
diff --git a/com.mojang.Minecraft.json b/com.mojang.Minecraft.json
index cac5f18..428a8ea 100644
--- a/com.mojang.Minecraft.json
+++ b/com.mojang.Minecraft.json
@@ -46,6 +46,16 @@
           "/usr/lib/sdk/openjdk11/install.sh"
         ]
     },
+    {
+      "name": "flite",
+      "sources": [
+        {
+          "type": "archive",
+          "url": "http://www.festvox.org/flite/packed/flite-2.1/flite-2.1-release.tar.bz2",
+          "sha256": "c73c3f6a2ea764977d6eaf0a287722d1e2066b4697088c552e342c790f3d2b85"
+        }
+      ]
+    },
     {
       "name": "minecraft",
       "buildsystem": "simple",
```

Unfortunately, it didn't help and there is still the `ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper': Native library (linux-x86-64/libfliteWrapper.so) not found in resource path` error in the game log.

**Comment by AsciiWolf** [comment]
It seems that the newest launcher depends on [Orca](https://wiki.gnome.org/Projects/Orca) for this.

**Comment by AsciiWolf** [comment]
`sh: line 1: orca: command not found`

Maybe we could try adding Orca as a module after #83 is merged?

**Comment by AsciiWolf** [comment]
I have tried adding Orca and its dependencies:

```
diff --git a/com.mojang.Minecraft.json b/com.mojang.Minecraft.json
index b7ab060..73f5d79 100644
--- a/com.mojang.Minecraft.json
+++ b/com.mojang.Minecraft.json
@@ -52,6 +52,49 @@
                 }
             ]
         },
+        {
+            "name": "pygobject",
+            "buildsystem": "meson",
+            "config-opts": [ "-Dpycairo=disabled", "-Dtests=false" ],
+            "sources": [
+                {
+                    "type": "archive",
+                    "url": "https://download-fallback.gnome.org/sources/pygobject/3.40/pygobject-3.40.1.tar.xz",
+                    "sha256": "00c6d591f4cb40c335ab1fd3e8c17869ba15cfda54416fe363290af766790035"
+                }
+            ]
+        },
+        {
+            "name": "at-spi2",
+            "buildsystem": "meson",
+            "sources": [
+                {
+                    "type": "archive",
+                    "url": "https://gitlab.gnome.org/GNOME/at-spi2-core/-/archive/AT_SPI2_CORE_2_40_3/at-spi2-core-AT_SPI2_CORE_2_40_3.tar.bz2",
+                    "sha256": "6012ee4010e8de3821a998924d6877d94b7e7e6daaf4cc770a043ec42e2e683d"
+                }
+            ]
+        },
+        {
+            "name": "pyatspi",
+            "sources": [
+                {
+                    "type": "archive",
+                    "url": "https://download-fallback.gnome.org/sources/pyatspi/2.38/pyatspi-2.38.1.tar.xz",
+                    "sha256": "e49f27e9e29c24ac3ccb837a7f221952532940da0344e7e8c0899924aeb98151"
+                }
+            ]
+        },
+        {
+            "name": "orca",
+            "sources": [
+                {
+                    "type": "archive",
+                    "url": "https://download-fallback.gnome.org/sources/orca/40/orca-40.0.tar.xz",
+                    "sha256": "0000eee390b906a0f5611eb601633bd5ec03d231662ee7d865d1016459fb0043"
+                }
+            ]
+        },
         {
             "name": "minecraft",
             "buildsystem": "simple",
@@ -113,4 +156,4 @@
             ]
         }
     ]
-}
\ No newline at end of file
+}
```

Unfortunately, it does not work. Narrator is still unavailable and Orca crashes when I try to run it manually:
```
$ orca

(orca:3): dbind-WARNING **: 23:46:12.525: Couldn't get application list: org.freedesktop.DBus.Error.AccessDenied
/app/lib/python3.8/site-packages/pyatspi/registry.py:206: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  return Atspi.get_desktop(i)
Traceback (most recent call last):
  File "/app/bin/orca", line 283, in <module>
    sys.exit(main())
  File "/app/bin/orca", line 280, in main
    return orca.main()
  File "/app/lib/python3.8/site-packages/orca/orca.py", line 795, in main
    if not _settingsManager.isAccessibilityEnabled():
  File "/app/lib/python3.8/site-packages/orca/settings_manager.py", line 349, in isAccessibilityEnabled
    rv = _proxy.Get('(ss)', 'org.a11y.Status', 'IsEnabled')
  File "/app/lib/python3.8/site-packages/gi/overrides/Gio.py", line 349, in __call__
    result = self.dbus_proxy.call_sync(self.method_name, arg_variant,
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown (2)
```

Orca seems to depend heavily on DBus and its dependencies even depend on some systemd parts. It will probably be quite hard to have it working inside Flatpak, but if anyone wants to help with this, I will be grateful.

**Comment by AsciiWolf** [comment]
I just realized that this is still not fixed entirely because there is no narrator in the Launcher itself. There probably is, but it also does not work inside the Flatpak - there is a `sh: line 1: orca: command not found` message in log every time I start the Launcher. I will however keep this issue closed since it is really hard to get Orca working inside Flatpak.
